const router = require("express").Router();
const c = require("../controllers/stockLedgerController");
const { protect } = require("../middleware/auth");
router.use(protect);
router.post("/", c.createStockLedger);
router.get("/", c.getStockLedgers);
router.get("/:id", c.getStockLedgerById);
router.put("/:id", c.updateStockLedger);
router.delete("/:id", c.deleteStockLedger);
module.exports = router;
